/**
 * QuizCard — Post-video comprehension quiz
 * Shows 2-3 multiple-choice questions generated by Gemini from transcript content.
 * Appears between video completion and the bridge/challenge card.
 */
import { useState, useMemo } from "react";
import PropTypes from "prop-types";
import quizData from "../../data/quiz_questions.json";

export default function QuizCard({ courseCode, videoKey, onComplete, onSkip }) {
  const [currentQ, setCurrentQ] = useState(0);
  const [selected, setSelected] = useState(null);
  const [revealed, setRevealed] = useState(false);
  const [score, setScore] = useState(0);
  const [finished, setFinished] = useState(false);

  // Find questions for this video
  const questions = useMemo(() => {
    if (!courseCode || !videoKey) return [];
    const courseQuiz = quizData[courseCode];
    if (!courseQuiz) return [];

    // Try exact match first, then normalized match
    if (courseQuiz[videoKey]) return courseQuiz[videoKey];

    const normalize = (s) =>
      (s || "")
        .replace(/\.mp4$/i, "")
        .replace(/^[\d._]+/, "")
        .replace(/[\s_]+/g, "")
        .toLowerCase();

    const normalizedKey = normalize(videoKey);
    for (const [key, qs] of Object.entries(courseQuiz)) {
      const nk = normalize(key);
      if (nk === normalizedKey || nk.includes(normalizedKey) || normalizedKey.includes(nk)) {
        return qs;
      }
    }
    return [];
  }, [courseCode, videoKey]);

  // No questions available — skip silently
  if (questions.length === 0) {
    return null;
  }

  const question = questions[currentQ];
  const isCorrect = selected === question?.correct;
  const totalQuestions = questions.length;

  const handleSelect = (index) => {
    if (revealed) return; // prevent re-selection after reveal
    setSelected(index);
  };

  const handleCheck = () => {
    if (selected === null) return;
    setRevealed(true);
    if (selected === question.correct) {
      setScore((s) => s + 1);
    }
  };

  const handleNext = () => {
    if (currentQ < totalQuestions - 1) {
      setCurrentQ((q) => q + 1);
      setSelected(null);
      setRevealed(false);
    } else {
      setFinished(true);
    }
  };

  const handleFinish = () => {
    onComplete({ score, total: totalQuestions });
  };

  // Score summary screen
  if (finished) {
    const percentage = Math.round((score / totalQuestions) * 100);
    const emoji = percentage >= 80 ? "🌟" : percentage >= 50 ? "👍" : "📖";
    const message =
      percentage >= 80
        ? "Excellent! You've got a strong grasp of this material."
        : percentage >= 50
          ? "Good effort! Consider rewatching for the topics you missed."
          : "You might want to re-watch this section before moving on.";

    return (
      <div className="quiz-card">
        <div className="quiz-score-summary">
          <div className="score-emoji">{emoji}</div>
          <h3>
            {score}/{totalQuestions} Correct
          </h3>
          <div className="score-bar">
            <div className="score-fill" style={{ width: `${percentage}%` }} />
          </div>
          <p className="score-message">{message}</p>
          <button className="quiz-continue-btn" onClick={handleFinish}>
            Continue →
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="quiz-card">
      <div className="quiz-header">
        <span className="quiz-icon">🧪</span>
        <h3>Quick Check</h3>
        <span className="quiz-progress">
          {currentQ + 1} / {totalQuestions}
        </span>
      </div>

      <p className="quiz-question">{question.question}</p>

      <div className="quiz-options">
        {question.options.map((option, i) => {
          let optionClass = "quiz-option";
          if (selected === i) optionClass += " selected";
          if (revealed) {
            if (i === question.correct) optionClass += " correct";
            else if (selected === i) optionClass += " incorrect";
          }
          return (
            <button
              key={i}
              className={optionClass}
              onClick={() => handleSelect(i)}
              disabled={revealed}
            >
              <span className="option-letter">{String.fromCharCode(65 + i)}</span>
              <span className="option-text">{option}</span>
              {revealed && i === question.correct && <span className="option-icon">✓</span>}
              {revealed && selected === i && i !== question.correct && (
                <span className="option-icon">✗</span>
              )}
            </button>
          );
        })}
      </div>

      {/* Explanation after reveal */}
      {revealed && question.explanation && (
        <div className={`quiz-explanation ${isCorrect ? "correct" : "incorrect"}`}>
          <span className="explanation-icon">{isCorrect ? "✅" : "💡"}</span>
          <p>{question.explanation}</p>
        </div>
      )}

      <div className="quiz-actions">
        {!revealed ? (
          <button className="quiz-check-btn" onClick={handleCheck} disabled={selected === null}>
            Check Answer
          </button>
        ) : (
          <button className="quiz-next-btn" onClick={handleNext}>
            {currentQ < totalQuestions - 1 ? "Next Question →" : "See Results →"}
          </button>
        )}
        <button className="quiz-skip-btn" onClick={onSkip}>
          Skip Quiz
        </button>
      </div>
    </div>
  );
}

QuizCard.propTypes = {
  courseCode: PropTypes.string,
  videoKey: PropTypes.string,
  onComplete: PropTypes.func.isRequired,
  onSkip: PropTypes.func.isRequired,
};
